/*
 * This file was automatically generated by EvoSuite
 * Tue Oct 16 13:59:03 GMT 2018
 */

package com.tv.tutorials.coolestuffvoorcheops.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.tv.tutorials.coolestuffvoorcheops.exceptions.StorageException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StorageException_ESTest extends StorageException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StorageException storageException0 = new StorageException((String) null, (Throwable) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StorageException storageException0 = new StorageException("5");
  }
}
